### PR TITLE
Fix AutoSpammer delay

### PR DESCRIPTION
**Pull request by DaMatrix**

### CODE REVIEW

**Comment by Vertex-Client** [comment]
Thanks for your PR, but there are errors in your code.

**Comment by DaMatrix** [comment]
I tried it and it ran fine on my client.

**Comment by Vertex-Client** [comment]
I meant for(;;), that code is similar to while(true), right? Why do you need that?

**Comment by Vertex-Client** [comment]
Ah, now I see why you used it.

**Comment by DaMatrix** [comment]
For some reason having the recursive function caused it to stop working after disabling and then reenabling.  This is also more efficient because it prevents the creation of tons of `Thread_` objects.

**Comment by Vertex-Client** [comment]
Ahah, I will look into it.

**Comment by Vertex-Client** [comment]
Done.

**Pull request merged**
