### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Erkam246**
:)

### CODE REVIEW

**Comment by Vertex-Client** [comment]
Lol, I'm not sure what to say about this. :S

**Comment by Erkam246** [comment]
nothing xD

**Comment by Vertex-Client** [comment]
Lol :)
Thanks for the support though :)
:+1:

**Comment by Erkam246** [comment]
Best hack can you make it server compatible

**Comment by Vertex-Client** [comment]
The Client is already server compatible, KillAura isn't possible on multiplayer. I'm sorry.

**Comment by Erkam246** [comment]
kill aura i will hack on server

**Comment by Vertex-Client** [comment]
Please open an issue if you're having any problems.

**Pull request closed without merging**
